version: "2"
services:
  base:
    image: python:3.9
    working_dir: /home/app
    volumes:
      - .:/home/app
  builder:
    extends:
      service: base
    command: /bin/bash -c "pip install -r requirements.dev.txt && pyinstaller scanner.spec"
  test:
    extends:
      service: base
    env_file: 
      - .env
    command: /bin/bash -c "pip install -r requirements.txt && cd src && python -m unittest"
  bash:
    extends:
      service: base
    stdin_open: true
    tty: true
    command: /bin/bash