version: "3.3"
services:
  app:
    image: derhenning/tgtg:latest
    environment: 
      - DEBUG=false                                   ## true for debug log messages
      - TGTG_USERNAME=                                ## TGTG Username / Login EMail
      - SLEEP_TIME=60                                 ## Time to wait till next scan in seconds - default 60 seconds
      - ITEM_IDS=                                     ## (optional) Comma seperated list of Item Ids to scan

      - SMTP=true                                     ## true = enable mail notifications via smtp
      - SMTP_HOST=smtp.gmail.com                      ## smtp Server - smtp.gmail.com for google
      - SMTP_PORT=465                                 ## smtp Server Port - 465 for google
      - SMTP_USERNAME=max.mustermann@gmail.com        ## smtp Login - your EMail for google
      - SMTP_PASSWORD=                                ## smtp Login Password - your Login PW for google
      - SMTP_TLS=true                                 ## enable TLS - true for google and most smtp servers
      - SMTP_SENDER=max.mustermann@gmail.com          ## sender adress - same as Login for google and most smtp servers
      - SMTP_RECIPIENT=max.mustermann@gmail.com       ## recipient for notifications - can be the same as sender

      - PUSH_SAFER=false                              ## true = enable notifications via pushsafer.com
      - PUSH_SAFER_KEY=
      - PUSH_SAFER_DEVICE_ID=

      - IFTTT=true                                    ## true = enable notifications via IFTTT Webhooks
      - IFTTT_EVENT=tgtg_notification                 ## IFTTT Webhooks Event
      - IFTTT_KEY=                                    ## IFTTT Webhooks Key