version: "2"
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /home/app
    volumes:
      - .:/home/app
  builder:
    extends:
      service: base
    command: pyinstaller scanner.spec
  test:
    extends:
      service: base
    env_file: 
      - .env
    command: python -m unittest discover -v -s ./src
  bash:
    extends:
      service: base
    stdin_open: true
    tty: true
    command: /bin/bash