version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment: 
      - DEBUG=true
    env_file: 
      - .env
    volumes:
      - ./src:/home/app
    command: python /home/app/scanner.py