name: Poetry Setup Action

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  setup-poetry:
    steps:
    - name: Setup Poetry
      run: |
        pip install --upgrade pip setuptools wheel poetry==${{ inputs.version }}
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
        poetry config installer.max-workers 1
