name: Package Application with Pyinstaller for Windows

on:
    push:
        branches:
            - main
        tags:
            - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
    - 
      name: Set Release Tag
      run: |
        if [ "${GITHUB_REF#refs/*/}" = "main" ]; \
        then echo "RELEASE_TAG=latest"; \
        elif [ "${GITHUB_REF#refs/*/}" = "dev" ]; \
        then echo "RELEASE_TAG=dev"; \
        else echo "RELEASE_TAG=${GITHUB_REF#refs/*/}"; fi \
        >> $GITHUB_ENV
    - 
      uses: actions/upload-artifact@v2
      with:
        name: scanner-win-${RELEASE_TAG}
        path: src/dist/scanner