name: Tests

on:
  pull_request:

jobs:
  tests:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install Poetry
      run: pip install --upgrade pip setuptools wheel && \ pip install "poetry==1.5.1"
    - name: Install dependencies
      run: poetry install --without build
    - name: Run linting
      run: poetry run pre-commit run -a
    - name: Run tests
      run: poetry run pytest -v -m "not tgtg_api" --cov --cov-report=xml
    - uses: codecov/codecov-action@v3
