name: Tests

on:
  pull_request:

jobs:
  tests:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Setup Poetry
      run: pip install --upgrade pip setuptools wheel poetry==1.5.1
    - name: Install dependencies
      run: poetry install
    - name: Run linting
      run: poetry run pre-commit run -a
    - name: Run tests
      run: poetry run pytest -v -m "not tgtg_api" --cov --cov-report=xml
    - name: Build executable
      run: |
        poerty run pyinstaller scanner.spec
        ./dist/scanner -v
    - uses: codecov/codecov-action@v3
