name: Tests

on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*
  pull_request:
  schedule:
    - cron: "0 1 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install -r requirements.dev.txt
      - name: Run tests
        working-directory: ./src
        run: |
          python -m unittest

          export ${{env.GITHUB_ENV}}
          echo Masking tokens ...

          echo befor masking:
          echo ${{env.TGTG_ACCESS_TOKEN}}
          echo ${{env.TGTG_REFRESH_TOKEN}}
          echo ${{env.TGTG_USER_ID}}


          echo ::add-mask::${{env.TGTG_ACCESS_TOKEN}}
          echo ::add-mask::${{env.TGTG_REFRESH_TOKEN}}
          echo ::add-mask::${{env.TGTG_USER_ID}}
          echo after masking:
          echo $TGTG_ACCESS_TOKEN
          echo $TGTG_REFRESH_TOKEN
          echo $TGTG_USER_ID

          echo TGTG_ACCESS_TOKEN="$TGTG_ACCESS_TOKEN" >> $GITHUB_ENV
          echo TGTG_REFRESH_TOKEN="$TGTG_REFRESH_TOKEN" >> $GITHUB_ENV
          echo TGTG_USER_ID="$TGTG_USER_ID" >> $GITHUB_ENV

        env:
          TGTG_USERNAME: ${{secrets.TGTG_USERNAME}}
          TGTG_ACCESS_TOKEN: ${{secrets.TGTG_ACCESS_TOKEN}}
          TGTG_REFRESH_TOKEN: ${{secrets.TGTG_REFRESH_TOKEN}}
          TGTG_USER_ID: ${{secrets.TGTG_USER_ID}}
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'TGTG_ACCESS_TOKEN'
          value: ${{env.TGTG_ACCESS_TOKEN}}
          repository: Der-Henning/tgtg
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'TGTG_REFRESH_TOKEN'
          value: ${{env.TGTG_REFRESH_TOKEN}}
          repository: Der-Henning/tgtg
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'TGTG_USER_ID'
          value: ${{env.TGTG_USER_ID}}
          repository: Der-Henning/tgtg
          token: ${{ secrets.REPO_ACCESS_TOKEN }}